Add support for MaxNode option with CBC solver
coin-or/pulp pull request #580
Opened 2022-09-22 10:32 UTC by E-Aho

This commit adds support for the `maxNodes` option for the CBC solver. Includes a simple test to make sure the option is implemented correctly.

I originally tried to create a test to show that using the `maxNodes` option would cause the CBC solver to terminate upon reaching that number of nodes, but couldn't find an intuitive way to read the `Enumerated Nodes` or "stopping reason" outputs of the sovler in test cases.

2022-09-22 10:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/coin-or/pulp?pullRequest=580) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/coin-or/pulp?pullRequest=580) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/coin-or/pulp?pullRequest=580) it.</sub>

2023-01-05 14:20 UTC, E-Aho commented
Pinging @pchtsp to check if there's any update on this PR :)

For reference, I've been using the change in this fork since raising the PR and it has been working fine

2023-03-12 23:13 UTC, pchtsp requested changes

2023-03-12 23:13 UTC, pchtsp commented on pulp/apis/core.py
> +        self.maxNodes = maxNodes
as the comment two lines below says, the maxNodes attribute is stored inside the `self.optionsDict` attribute.

2023-03-12 23:13 UTC, pchtsp commented on pulp/apis/coin_api.py
> +        if self.maxNodes is not None:
As the other comment says, this attribute does not exist. You should thus do something like:
```
maxNodes = self.optionsDict.get("maxNodes")
if maxNodes is not None:
    cmds += f"maxNodes {maxNodes} "
```

2023-10-02 10:08 UTC, pchtsp commented
sorry for the troubles, I've added the maxNodes argument as explained in the comments https://github.com/coin-or/pulp/pull/690. I'm closing the PR.

2023-10-02 10:08 UTC, closed without merging